### ISSUE TITLE
Lower case pipetrick

### ISSUE THREAD

**Issue by JeppeKlitgaard** [marcusolsson/obsidian-pipe-tricks#1]
I am really enjoying pipe tricks so far.

I am wondering if a useful additional trick beyond the Wikimedia spec would be a lowering trick:

`[[Gravitational Mass|_]]` → `gravitational mass`.

Alternatively the underscore could be placed after the wiki-style link:

`[[Gravitational Mass|]]_` → `gravitational mass`.

It is certainly something I would find very useful. I could even have a go at a PR if this is something you'd take a PR for. Potentially it could be enabled/disabled using a setting.

This could be extended to title and upper case as well with symbols like `^` and `^^`

**Comment by JeppeKlitgaard** [comment]
Would you take a PR that extends this plugin to implement "pipe functions"?

**Comment by marcusolsson** [comment]
Closing with #5.
