### ISSUE TITLE
[Bug] Assumes non-null `nextSibling`

### ISSUE THREAD

**Issue by JeppeKlitgaard** [marcusolsson/obsidian-pipe-tricks#2]
Sometimes raises: `TypeError: Cannot read property 'nodeType' of null`

`sibling` in `blendSuffix` may be null

**Comment by etiennepellegrini** [comment]
Bumping this - the nodeType error creates problems with dataview's task lists.

For instance:

~~~
```dataview
dv.taskList(dv.pages().file.tasks, true)
```
~~~
raises the error

**Comment by JeppeKlitgaard** [comment]
This is fixed in #5 

@etiennepellegrini you can download the PR and compile it if you need the feature now. I have a busy few days ahead of me, so I won't get around to doing the proposed changes on the PR before then.
