### ISSUE TITLE
Problem with updating, then installing

### ISSUE THREAD

**Issue by OlivierPS** [marcusolsson/obsidian-pipe-tricks#7]
Hi Marcus,
I enjoyed this plugin very much. Then I came into this issue: the update mechanism failed with the message “Failed to install plugin “Pipe tricks””. So, I tried to uninstall it then reinstalling, but the same happened. So, I’m now without this plugin… 😒
Can you help me?
Thank you very much.
Olivier :-{)

My address: olivierps@icloud.com

**Comment by kazi-kavish** [comment]
I am facing the same issue. I tried a manual install too but it asks me to update it from within Obsidian and the update fails.

**Comment by Hwiet** [comment]
I also tried to download this addon and try it. In the Developer Console, I am getting the error

```
Failed to load resource: the server responded with a status of 404 () https://github.com/marcusolsson/obsidian-pipe-tricks/releases/download/1.1.0/manifest.json
```

The plugin "market" shows the current version to be 1.1.0, so I assume it's trying to fetch the manifest from the 1.1.0 release, which does not exist yet (the lastest release in this repository is version 1.0.1). Perhaps releasing this new version will solve the problem?

**Comment by marcusolsson** [comment]
@Hwiet Thanks for the heads-up! I've triggered a new release for 1.1.0. Could you verify that it works?

**Comment by qifei9** [comment]
> @Hwiet Thanks for the heads-up! I've triggered a new release for 1.1.0. Could you verify that it works?

I can install it now.

**Comment by Hwiet** [comment]
@marcusolsson I am also able to install now.
